### PR TITLE
Fixing the styling and link of  navigation bar

### PR DESCRIPTION
**Pull request by shubhsk88**
This PR address the styling of the navigation bar which was opening from left side and also changing the styling of the ask the question button .While the other changes are made by my editor which was using prettier

### CODE REVIEW

**Comment by noahub** [comment]
Hey @shubhsk88, nice job getting this PR up. I see there's lots of different functionality being updated here, and it looks like there are quite a few conflicts with master.

Something that might help is splitting this into separate PRs based on the specific functionality changes being made. It'll make it easier for you to resolve the merge conflicts and will make the code easier to review too!

**Comment by aviskarkc10** [comment]
@shubhsk88 Thanks for you PR. Since you are making changes to styling, it would be awesome if you could add some screenshots. It'd make the reviewing the PR that much easier.

**Comment by nthopinion** [comment]
Hi @shubhsk88  The branch has conflicts... Please review with the latest commit. Also check out the current site. Thanks

**Comment by shubhsk88** [comment]
I also tried to do the same changes as it is updated in the site

**Pull request closed without merging**
