### PR TITLE
Do not merge: multilingual-support Readme update

### PR DESCRIPTION
**Pull request by nastikue**
## Motivation

Trello: https://trello.com/c/tToXdGAY/58-multilingual-support

## Implementation

Updates to be merged: Readme updated with adding chapter Localization
FE updates to be reverted before merge: i18n config, actions/question.js, containers/PatientBoard.js (commit 0750a46f6f08cc426b12cbcd82533dfd30d38883)
BE updates to be reverted before merge: app, api/public/locales/ (commit b91ad2368ddc799d4e31a086303ceca0498633bd)

## Screenshots/Links

In temp example you can see:
1. translations are received from BE http://prntscr.com/ry1ab3
2. language changes can be provided during fetch http://prntscr.com/ry16ud

### CODE REVIEW

**Comment by sethuraj** [comment]
@nastikue I am going to merge this to test. The language paramater "de" or "en", these should then be passed to the api to get the translated data.

**Comment by nastikue** [comment]
@sethuraj I've added example of how language can be received from i18n in component and passed in fetch, please provide me example of endpoint with language set in the header and I'll make a better example.

**Comment by sethuraj** [comment]
@nastikue We have a version already implemented for the translation. We have a multi answer change coming in, I would like you to fork that code review it and then make the necessary language change. SO have this branch saved locally in your fork and close this PR for now. Thanks Jay

**Comment by nastikue** [comment]
@sethuraj , this PR was for info purposes only, closing it...

**Pull request closed without merging**
