### PR TITLE
Fix handler for submitting reported question

### PR DESCRIPTION
**Pull request by christianlomboy**
## Motivation

Error when submitting a reported question in dev environment

## Implementation

Binding the value of 'this' to handleSubmitReportIssue function

## Screenshots/Links

N/A

### CODE REVIEW

**Comment by aviskarkc10** [comment]
@christianlomboy thanks a lot for fixing this issue. Can you also check if we need to do this for other functions in the same `QuestionBoard` file?

**Comment by christianlomboy** [comment]
@aviskarkc10 no problem! And yes, I’ll get on that tomorrow.

**Comment by aviskarkc10** [comment]
Awesome thanks. Don't look into the issue in other files. It would probably be too much for one person, but if you could fix issues in this file, that'd be super :)

**Comment by sethuraj** [comment]
@aviskarkc10 Since you have reviewed this, I will let you merge this. Should this go to develop/registrationForm only or should it go live and also be merged to develop tracks? Thanks Jay

**Comment by aviskarkc10** [comment]
@sethuraj this should be released actually. It's a bug that causes the application to crash

**Comment by sethuraj** [comment]
Ok I wanted to make sure. Thanks Aviskar and Christian

**Comment by christianlomboy** [comment]
@sethuraj sure! And @aviskarkc10 I apologize I didn’t get a chance to look thru the code yesterday. I will check it out by end of day today and create another PR if any other issues are found. Thanks!

**Comment by christianlomboy** [comment]
@aviskarkc10 reading thru the QuestionBoard.js code, it seems like all other functions are handled using arrow function expressions.

**Comment by aviskarkc10** [comment]
Thanks awesome @christianlomboy

**Pull request merged**
