### PR TITLE
README.md minor fix

### PR DESCRIPTION
**Pull request by joannakwh**
[Issue #16](https://github.com/nthopinion/covid19/issues/16) 

- links are clickable and formatted correctly
- readme no longer showing a HTML code block

### CODE REVIEW

**Comment by nthopinion** [comment]
Hi @joannakwh  
We had two other updates on Read me, so there is a minor conflict, can you please pull the latest and make your changes and do a pull request again. We need your change to fix the Read me. Thanks

**Comment by joannakwh** [comment]
@nthopinion I synced up the changes on my local branch and resolved the conflict. I think that means the pull request will work now. Let me know if I'm mistaken. Thanks!

**Comment by tendermario** [comment]
LGTM. 👍

I believe you could have rebased master onto your branch, just a tip. :)

**Comment by nthopinion** [comment]
Thanks @joannakwh

**Pull request merged**
